export default {
    PESO_BAJO_COLOR : "#22D70F",
    PESO_NORMAL_COLOR : "#21EE43",
    SOBRE_PESO_COLOR : "#DDDA1C",
    SOBRE_PESO1_COLOR : "#EAA716",
    SOBRE_PESO2_COLOR : "#F16C0A",
    RIESGOSO_COLOR : "#FE1B00",
    DEFAULT_COLOR : "#228DD4",
}